spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: sravan
    password: java
    driver-class-name: oracle.jdbc.driver.OracleDriver  jpa:    hibernate:      ddl-auto: update
  application:    name: Payment-Service
server:  port: 8082
  
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
         defaultZone: http://localhost:8761/eureka  instance:    prefer-ip-address: true            
        